name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build
    - run: nix flake check
    - run: nix run .#oci-image.copyToPodman
    - run: podman tag simmsb/container-per-ip simmsb/container-per-ip:${{ github.ref_name }}

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.6
      with:
        registry: ghcr.io
        image: "simmsb/container-per-ip"
        tags: ${{ github.ref_name }} latest 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
